version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_SERVER_PORT}:80"
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/server
    environment:
      - TZ=${TZ}

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    working_dir: /var/www/server
    tty: true
    depends_on:
      - mysql
    volumes:
      - ../:/var/www/server
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini

  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  mysql-data:
    external: false